update docker compose agent and upload test result, Extraction data.

diff --git a/chatbot-api/docker-compose.yaml b/chatbot-api/docker-compose.yaml
--- a/chatbot-api/docker-compose.yaml
+++ b/chatbot-api/docker-compose.yaml
@@ -4,8 +4,8 @@ services:
     container_name: neo4j-admin
     restart: "no"
     volumes:
-      - ../../neo4j/data:/data
-      - ../../neo4j/backups:/backups
+      - ../neo4j/data:/data
+      - ../data:/backups
     entrypoint: >
       /bin/sh -c "
       if [ ! -f /data/.db_loaded ]; then
@@ -30,8 +30,8 @@ services:
       - NEO4J_server_config_strict__validation_enabled=false
 
     volumes:
-      - ../../neo4j/data:/data
-      - ../../neo4j/plugins:/plugins
+      - ../neo4j/data:/data
+      - ../neo4j/plugins:/plugins
     depends_on:
       - neo4j-admin
 
@@ -42,17 +42,21 @@ services:
     ports:
       - 8000:8000
     env_file: ".env"
-    command: gunicorn --bind=0.0.0.0 -w 4 -k uvicorn.workers.UvicornH11Worker main:app -t 180 --keep-alive 180
+    command: gunicorn --bind=0.0.0.0 -w 2 -k uvicorn.workers.UvicornH11Worker main:app -t 360 --keep-alive 3600
+    volumes:
+      - ../embedding_model:/bot-server/src/chains/embedding_model:rw
     depends_on:
       - neo4j
+    extra_hosts:
+      - 'host.docker.internal:host-gateway'
 
-  cf-tunnel:
-    image: cloudflare/cloudflared:latest
-    container_name: cf-tunnel
-    restart: always
-    env_file: ".env"
-    entrypoint: > 
-      /bin/sh -c "if [ -z \"$CLOUDFLARE_TUNNEL_TOKEN\" ]; then
-        echo 'CLOUDFLARE_TUNNEL_TOKEN is missing'; exit 1; 
-      fi
-      && tunnel --no-autoupdate run --protocol http2 --token $CLOUDFLARE_TUNNEL_TOKEN"
+        #  cf-tunnel:
+        #    image: cloudflare/cloudflared:latest
+        #    container_name: cf-tunnel
+        #    restart: always
+        #    env_file: ".env"
+        #    entrypoint: > 
+        #      /bin/sh -c "if [ -z \"$CLOUDFLARE_TUNNEL_TOKEN\" ]; then
+        #        echo 'CLOUDFLARE_TUNNEL_TOKEN is missing'; exit 1; 
+        #      fi
+        #      && tunnel --no-autoupdate run --protocol http2 --token $CLOUDFLARE_TUNNEL_TOKEN"
